### ISSUE TITLE
Ingest and assign relationships for test data through console or UI?

### ISSUE THREAD

**Issue by njaffer** [mlibrary/hydra-prototype#2]
Ingest sample data from Deep Blue through console

**Comment by blancoj** [comment]
I'm working on this.

**Comment by respinos** [comment]
For reference on running ad-hoc scripts: https://mattbrictson.com/running-and-destroying-rails --- but there are rake tasks for importing seed data, so that sounds appropriate as well.

Rake tasks can be targeted/organized by environment: http://stackoverflow.com/a/591912
