### ISSUE TITLE
Customize main page

### ISSUE THREAD

**Issue by njaffer** [mlibrary/hydra-prototype#3]
Edit header, title and other labels on the main page

**Comment by gordonleacock** [comment]
I'm working on this one today 2015-10-05.

**Comment by gordonleacock** [comment]
This one is complete and up on gordonleacock in branch main-page. It was a little weird because the file was in the .bundle directory which grep wasn't searching. I changed the .gitignore file before committing and uploading to gordonleacock.

**Comment by respinos** [comment]
To make local customizations, I think you want to copy that file into the app's structure and modify there (vs. within the .bundle). Does that work?

**Comment by gordonleacock** [comment]
Thanks Roger, Jose said the same thing. I made the changes as suggested. I made a pull request but don't have write access yet.
