### ISSUE TITLE
Create UI for collection admin to add deposoitors

### ISSUE THREAD

**Issue by respinos** [mlibrary/hydra-prototype#38]
e.g. UI for User with permission to add depositors to select users and assign role

**Comment by gordonleacock** [comment]
This is now pending some investigation by roger, nabeela, and myself. One key issue is do we store collection_managers and collection_depositors as 1) part of the collection meta data or 2) in a db using active record. A second key issue is how do we enable the proper permissions using that data in the various collection use cases (create a new collection, edit a collection, delete a collection, etc) presumably in the appropriate controllers.

I had been going down path 1) when we decided this need more investigation. Jose send a message to hydra-tech asking about people previous experiences with this issue which you can see here together with a response from Justin (https://groups.google.com/forum/#!topic/hydra-tech/-1IIzDP8U7U).
