### ISSUE TITLE
Resolve curation concerns 0.2 conflicts with hydra prototype

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/hydra-prototype#44]
These conflicts appear when you try to run the rails server as errors in (at least) the redis and resque yml files. The conflicts don't appear when we change the Gemfile cc line to use version 0.1.

**Comment by njaffer** [comment]
Solution: Copied redis_config.rb and resque_config.rb from here: https://github.com/projecthydra-labs/curation_concerns/tree/master/curation_concerns-models/lib/generators/curation_concerns/models/templates/config
