### ISSUE TITLE
Explore Leases

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/hydra-prototype#64]
Research how leases are done in curation concerns by adding an item and placing a lease on it. Investigate how deep blue, publishing, and research data may currently be using leases or plan to use leases in the future.

**Comment by njaffer** [comment]
The Superuser can view and add lease. The app supports this feature

The Collection manager can view and add lease for all the collection he/she owns. (Is not supported yet)

The Collection depositor can view and add lease for all the collection he/she deposited to. (Is not supported yet)
