### ISSUE TITLE
Create RDF vocabularies

### ISSUE THREAD

**Issue by njaffer** [mlibrary/hydra-prototype#7]

**Comment by respinos** [comment]
Qualified DC is in RDF::Vocab::DC (e.g. RDF::Vocab::DC.abstract).

The qualified DC classes are in RDF::Vocab::DCMIType (FYI)

Setting up the local vocab as DeepBlue::Vocab.

**Comment by njaffer** [comment]
Thank you @respinos , Jose and I are working on creating models, this would help us in using these metadata

**Comment by blancoj** [comment]
I'm going to add to what Roger has done already.
